<?php 
    $category = $this->category;
    //print_r($category);
?>
<form action = "addcategory/themloaisp" method = "post" enctype="multipart/form-data">
<table width="100%">
	<tr>
		<td width="140"><span class="nameinput">Tên loại sản phẩm: </span></td>
		<td><input class="inputstyle" type="text" name="tenlsp" id="tenlsp" value="<?php echo $category[0]['tenloaisp'] ?>"/></td>
	</tr>
	<tr>
		<td><span class="nameinput">vị trí: </span></td>
		<td><input class="inputstyle" type="text" name="vitri" id="vitri" value="<?php echo $category[0]['vitri'] ?>"/></td>
	</tr>
    <tr>
		<td><span class="nameinput">Hiển thị: </span></td>
		<td><label><input type="checkbox" value="" name="anhien" id="anhien" <?php if($category[0]['anhien']==1) echo "checked='checked'"; ?> /> (bỏ chọn để ẩn loại sản phẩm này)</label></td>
	</tr>
	
</table>
<input type="hidden" id="idcategory" value="<?php echo $category[0]['idloaisp'] ?>"/>
<input type="button" name="btnsubmit" value="Cập Nhật Loại Sản Phẩm"
    onclick = "CapNhatLoaiSanPham(document.getElementById('idcategory').value, document.getElementById('tenlsp').value, document.getElementById('vitri').value, document.getElementById('anhien').checked)"
/>
</form>












