<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/default/css/style.css'; ?>"></link>
        <title><?php echo $this->app_title; ?></title>
    </head>

    <body>
        <div id="wrapper" class='wrapper'>            
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>