<?php 
$pagename = $_GET['pagename'];
$pageid = $_GET['pageid'];
//$articleid = $_GET['articleid'];
//
//if($articleid > 0 )
//{
//	echo $articleid;
//	echo $this->articledetail->tieu_de;
//	
//	
//}
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<form method="post" action="<?php echo APP_DOMAIN?>/admin/article/save" enctype="multipart/form-data">
<center>
	<h1><?php echo $pagename ?></h1>
</center>
<div class="nut_page">
	<input type="submit" name="submit" value="Lưu">
</div>


<div>
	<div class='page_cat'>
		<div class='page_title' >
		Tiêu đề
		</div>
		
	<div class='page_input'>			
			<input class="input500" type="text" name="tieu_de" size="50px" id="tieu_de" value="<?php echo $this->tieu_de ?>">
		</div>
	</div>


	<div class='page_cat'>
		<div class='page_title' >
		Tên menu
		</div>
		
	<div class='page_input'>			
			<input class="input500" type="text" name="ten_menu" size="50px" id="ten_menu" value="<?php echo $this->ten_menu ?>">
		</div>
	</div>
	


	<div class='page_cat'>
		<div class='page_title' >
		Thứ tự
		</div>
		
	<div class='page_input'>			
			<input class="input500" type="text" name="thu_tu" size="50px" id="thu_tu" value="<?php  echo $this->thu_tu ?>">
		</div>
	</div>
	
	
	<div class='page_cat'>
		<div class='page_title' >
		Ẩn/Hiện
		</div>
		
	<div class='page_input'>			
			<input type="checkbox" <?php  if($this->an_hien==1)echo " checked='checked' " ?>  value="1" name="an_hien">  ( Check vào là hiển thị )
		</div>
	</div>
	 
	 <br/>
	 <br/>
	 <br/>

	 
	<div class='page_cat'>
		<div class='page_title' style=" margin-top: 16px;">
		Nội dung
		</div>
		<br/>
		<br/>
		<br/>
		<br/>
		<div class='page_input'>
			
		</div>
		<textarea class="textarea700" name="noi_dung" id="noi_dung" style="text-align:left;height: 55px; width: 500px; resize: none; border: medium 1;"><?php echo $this->noi_dung ?></textarea>

	</div>
	
	
	
	
            
            
	
</div>
<input type='hidden' value='<?php echo $pageid ?>' name='id_fb_page' />
<input type='hidden' value='<?php echo $this->id_bai_viet ?>' name='id_bai_viet' />
</form>


		
		
		