<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title>giao dien 1</title>

<?php
//	echo $this->headLink ()
//			->appendStylesheet ( $this->baseUrl ('public/css/reset.css'))
//			;
//			
//
//	echo $this->headScript ()
//			->appendFile ( $this->baseUrl ( '/public/js/config.js' ) )
//			
//			;
		
?>

  </head>
  <body style="<?php echo $this->bodystyle; ?>">
    <?php  echo $this->render('_header.phtml')?>
	<div id="" class="wrapper">
	<?php echo $this->layout()->content; ?>	
	</div>
	<?php  echo $this->render('_footer.phtml')?>
    
</body>
</html>
