	         	<?php 
	         	$anhien = $_GET['status'];
    			$id_thi_sinh = $_GET['idthisinh'];
    			 if($anhien == 0)
		        {
		        	$an_hien = 1;
		        }else{
		        	$an_hien = 0;
		        }
	         	?>
	         	<div id="an_hien_thisinh_<?php echo $id_thi_sinh?>">
			          <?php 
			          if($an_hien == 1)
			          {
						?>
						    <a href='javascript:void(0)'  onClick="updatestatus_thisinh('<?php echo $an_hien?>', '<?php echo $id_thi_sinh?>')" >
								<img   src="<?php echo $this->baseUrl ('application/templates/giaodien_admin/images/publish_g.png') ?>" />
							</a>
						<?php 
			          }else{
			          ?>
			           <a href='javascript:void(0)'  onClick="updatestatus_thisinh('<?php echo $an_hien?>', '<?php echo $id_thi_sinh?>')" >
							<img   src="<?php echo $this->baseUrl ('application/templates/giaodien_admin/images/publish_r.png') ?>" />
						</a>
						<?php 
			          }
			          ?>
	          </div>