<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/css/style.css'; ?>"></link>
<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/jquery-1.8.0.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/main.js'; ?>"></script>
<script>
	var taaa = {};
	taaa.appdomain = "<?php echo APP_DOMAIN ?>";
	taaa.fbappdomain = "<?php echo FB_APP_DOMAIN ?>";
</script>
<title>Apps Store</title>

</head>

<body>


	<div id="container">
    	<div id="banner"></div><!--End #banner-->
    	<div id="main_nav">
        <?php 
            $id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
            $store = App_Models_StoreModel::getInstance();
            $category = $store->GetidCategory(); 
        ?>
        	<ul class="menu">
            <a href="index"><li <?php if($id=="") echo "class='active'";?> >Home</li></a>
            <?php 
                for($i=0; $i<count($category); $i++)
                {
            ?>
            	<a href="category?id=<?php echo base64_encode($category[$i]["idloaisp"]) ?>">
                    <li <?php if($id == base64_encode($category[$i]["idloaisp"])) echo "class='active'"; ?>><?php echo $category[$i]["tenloaisp"] ?></li>
                </a>
            <?php 
                } 
            ?>
            </ul>
        </div><!--End #main_nav-->
        <div id="content">
        	<?php echo $this->layout()->content; ?>
        </div><!--End #content-->
        <div id="footer">Powered by ISHALI MEDIA</div><!--End #footer-->
        
	</div><!--End #container-->
</body>
</html>
