<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title>Question & Answer Social Network</title>

<?php
	echo $this->headLink ()
			->appendStylesheet ( $this->baseUrl ('public/css/reset.css'))
			->appendStylesheet ( $this->baseUrl ('public/css/style.css'))

			;
			

	echo $this->headScript ()
			->appendFile ( $this->baseUrl ( '/public/js/config.js' ) )
 			->appendFile ( $this->baseUrl ( 'public/js/jquery.1.7.2.min.js' ) )
			
			;
		
?>

  </head>
  <body>
    <?php // echo $this->render('_header.phtml')?>
	<div id="" class="wrapper">
	<?php echo $this->layout()->content; ?>	
	</div>
	<?php // echo $this->render('_footer.phtml')?>
    
</body>
</html>
