<?php
    $showsp = $this->showsp;
    $idcat = $_GET['id'];
    if(isset($this->sotrang))
    {
       $sotrang = $this->sotrang; 
    }
?>
<div id="product">
	<ul class="pro">
        <?php
            for($i=0; $i<count($showsp); $i++)
            {  
        ?>
    	<li <?php if(($i+1)%4==0) echo "class='pro_last'"; ?>>
        	<a href="product?id=<?php echo base64_encode(stripslashes($showsp[$i]["idloaisp"])) ?>&sp=<?php echo base64_encode(stripslashes($showsp[$i]["idsp"]))?>">
            	<img src="<?php echo APP_DOMAIN . '/application/layouts/tmpstore/images/upload/images/' . $showsp[$i]["hinhchinh"]?>" alt="<?php echo $showsp[$i]["tensp"] ?>" title="<?php echo $showsp[$i]["tensp"] ?>" />
            </a>
            <a class="pro_name" href=""><?php echo $showsp[$i]["tensp"] ?></a>
            <p class="pro_price"><?php echo number_format($showsp[$i]["gia"],0,',','.') ?> VNĐ</p>
        </li>
        <?php } ?>
    </ul>
</div>
<?php 
    if(isset($sotrang))
    {
?>
    <div class="page">
        <ul class="ulpage">
        <?php
            if(!isset($_GET['page']))
            {
                echo "<a class='page_open' href='javascript:;'><li>1</li></a>";
                    
                for($i=2; $i<=$sotrang; $i++)
                {
                        echo "<a href='category?id=". $idcat ."&page=". base64_encode($i) ."'><li>". $i ."</li></a>";
                }
            }
            else
            {
                $npage = base64_decode($_GET['page']);
                
                for($i=1; $i<=$sotrang; $i++)
                {
                    if($i== $npage)
                        echo "<a class='page_open' href='javascript:;'><li>". $npage ."</li></a>";
                    else
                        echo "<a href='category?id=". $idcat ."&page=". base64_encode($i) ."'><li>". $i ."</li></a>";
                }
            }
        ?>
        </ul>
    </div>
<?php } ?>




































