<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/css/style.css'; ?>"></link>

        <script src="<?php echo APP_DOMAIN . '/public/js/modal.popup.0.2.js'; ?>" type="text/javascript"></script>      
        <script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/jquery-1.7.2.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/common.js'; ?>"></script>
        
        <title><?php echo $this->appTitle; ?></title>
        
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    </head>

    <body style="<?php echo $this->bodystyle; ?>">
        <div id="wrapper" class="wrapper">
		<?php 
		if($this->page->banner != "")
		{
		?>
            <div id="banner">
                <a href="<?php echo $this->page->banner_link; ?>" target="_blank">
                    <img width='770px' height='220px' src="<?php echo APP_DOMAIN; ?>/public/images/banner/<?php echo $this->page->banner; ?>" />
                </a>
            </div>
		<?php
		}
		?>
            <div class="clear"></div>
            <div id="header">
                <ul class="topmenu">
                    <li><a href="<?php echo APP_DOMAIN; ?>">Home</a></li>
                    <?php foreach ($this->listMenu as $menu) { ?>
                        <li>
                            <a href="<?php echo APP_DOMAIN . '/article?articleId=' . $menu->id_bai_viet ?>">
                                <?php echo $menu->ten_menu; ?>
                            </a>
                        </li>
                    <?php } ?>
                    <?php if ($this->page->like_tham_gia == 1) { ?>
                        <li><a href="<?php echo APP_DOMAIN; ?>/manage/join">Tham gia</a></li>
                    <?php } ?>
                    <?php // if ($this->id_user == $this->page->id_fb) { ?>
<!--                        <li><a href="<?php echo APP_DOMAIN; ?>/manage/config">Manage</a></li>-->
                    <?php // } ?>
                </ul>
            </div>
            <div class="clear"></div>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
            <div class="clear"></div>
            <div id="footer">
                <?php echo $this->appFooter; ?>
            </div>

        </div>
    </body>
</html>