<script>
    $(function(){
        //alert('aaaaaaaaaa');
      center()//gọi hàm mới load web
      //alert('aaaaa');
        $(window).resize(function(){center()})//gọi hàm khi resize
        //alert($(window).width());
      function center(){//hàm xử lý
        $('#dathang').css({left:($(window).width()-$('div#dathang').width())/2,top:(($(window).height()-$('div#dathang').height())/2)-100})
      }
    })
</script>
<?php
    $splienquan = $this->splienquan;
    //print_r($splienquan);
?>
<div id="dathang">
    <p class="close_dathang"></p>
    <div id="nd_dathang">
        <p class="title_dathang">
            Nhập thông tin đặt hàng
        </p>
        <table width="100%">
            <tr>
                <td width="100"><span class="text2">Họ tên:</span></td>
                <td><input class="input1" type="text" name="hoten" id="dh_hoten" /></td>
            </tr>
            <tr>
                <td><span class="text2">Số điện thoại:</span></td>
                <td><input class="input1" type="text" name="sdt" id="dh_sdt" /></td>
            </tr>
            <tr>
                <td><span class="text2">Email:</span></td>
                <td><input class="input1" type="text" name="email" id="dh_email" /></td>
            </tr>
            <tr>
                <td><span class="text2">Địa chỉ:</span></td>
                <td><input class="input1" type="text" name="diachi" id="dh_diachi" /></td>
            </tr>
            <tr>
                <td><span class="text2">Ghi chú:</span></td>
                <td><textarea class="input2" type="text" name="ghichu" id="dh_ghichu"></textarea></td>
            </tr>
            <tr>
                <td><span class="text2">Sản phẩm:</span></td>
                <td>
                    <span class="sp_dathang">Nam003 - Áo thun nam</span>
                    <input type="hidden" id="dh_sanpham" value="ao" />
                </td>
            </tr>
            <tr>
                
                <td colspan="2">
                    <p id="warning"></p>
                    <p onclick="DatHang(document.getElementById('dh_hoten').value, document.getElementById('dh_sdt').value, document.getElementById('dh_email').value, document.getElementById('dh_diachi').value, document.getElementById('dh_ghichu').value, document.getElementById('dh_sanpham').value)" class="bt_dathang">Đặt hàng</p>
                </td>
            </tr>
        </table>
        
    </div>
</div>

<?php
    $sanpham = $this->sanpham;
?>
<div id="anhdaidien">
	<div class="anhchinh">
		<img class="hinhchinh" src="<?php echo APP_DOMAIN . '/application/layouts/tmpstore/images/upload/images/' . $sanpham[0]["hinhchinh"]?>" alt="<?php echo $sanpham[0]["tensp"]?>" title="<?php echo $sanpham[0]["tensp"]?>" />
	</div>
	<div class="anhphu">
		<ul class="aphu">
            <li><a href="javascript:;"><img class="hinhphu1" src="<?php echo APP_DOMAIN . '/application/layouts/tmpstore/images/upload/images/' . $sanpham[0]["hinhchinh"]?>" alt="image" title="Chọn để thay đổi ảnh" /></a></li>
        <?php 
            $hinhphu = $sanpham[0]["hinhphu"];
            //echo $hinhphu;
            $hp = explode(',', $hinhphu);
            //print_r($hp);
            $j=2;
            for($i=0; $i<count($hp); $i++)
            {
        ?>
			<li><a href="javascript:;"><img class="hinhphu<?php echo $j; ?>" src="<?php echo APP_DOMAIN . '/application/layouts/tmpstore/images/upload/images/' . $hp[$i] ?>" alt="image" title="Chọn để thay đổi ảnh" /></a></li>
        <?php 
            $j++; }
        ?> 
		</ul>
	</div>
</div>
<div id="thongtin">
	<p class="masp">Mã sản phẩm : <?php echo $sanpham[0]["masp"]?></p>
	<h1 class="tensp"><?php echo $sanpham[0]["tensp"]?></h1>
    <p class="giaban"><?php echo number_format($sanpham[0]["gia"],0,',','.')?> VNĐ</p>
   
    <p class="order">Đặt hàng</p>
    
	<p class="text1">Mô Tả</p>
	<h2 class="motasp"><?php echo $sanpham[0]["mota"]?></h2>
	<p class="text1">Chi Tiết</p>
	<h3 class="chitietsp"><?php echo $sanpham[0]["chitietsp"]?></h3>
    
    <div class="chiase">
        <a title="Chia sẻ lên Zing Me" target="_blank" href="http://link.apps.zing.vn/share?u="><img src="http://ishali.com.vn/public/default/images/small_zing_icon.png"/></a>
    	<a title="Chia sẻ trên Google" target="_blank" href="https://plus.google.com/share?url="><img alt="Google +1" src="http://ishali.com.vn/public/default/images/icon_googleplus.jpg"/></a>
    	<a title="Chia sẻ trên Facebook" target="_blank" href="https://www.facebook.com/sharer/sharer.php?s=100&p[title]=<Title hien thi>&p[url]=<Url Hien Thi>%23share_button_top&p[images][0]=<Hinh Anh Hien thi>&p[summary]=<Mo Ta>"><img alt="Facebook" src="http://ishali.com.vn/public/default/images/icon_facebook.png"/></a>
    </div>
    
    
    <div class="splienquan">
    <p class="text1">Sản phẩm liên quan</p>
        <ul class="splienquan">
        <?php 
            for($i=0; $i<count($splienquan); $i++)
            {
        ?>
            <li><a href="product?id=<?php echo base64_encode($splienquan[$i]['idloaisp']); ?>&sp=<?php echo base64_encode($splienquan[$i]['idsp']); ?>"><img src="<?php echo APP_DOMAIN . '/application/layouts/tmpstore/images/upload/images/' . $splienquan[$i]['hinhchinh'] ?>" /></a></li>
            
        <?php } ?>
        </ul>
    </div>

</div>