<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/"><head>
        <title>Photo Gallery</title>  
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="canvas_admin.css">
		<script>
			var taaa = {};
			taaa.appdomain = "<?php echo APP_DOMAIN ?>";
			taaa.fbappdomain = "<?php echo FB_APP_DOMAIN ?>";
		</script>
        
        <script src="<?php echo APP_DOMAIN . '/public/js/modal.popup.0.2.js'; ?>" type="text/javascript"></script>
		<?php
			echo $this->headLink ()
					// ->appendStylesheet ( $this->baseUrl ('public/css/style.css'))
					->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/css/ishali_admin.css'))
					->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/css/jquery-ui.css'))
					;
					
		
			echo $this->headScript ()
					->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery-1.8.0.min.js') )
                    ->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/script.js') )
                    
					->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/aj.js') )
					->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/script.js') )
					
					
					//->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery.min.js') )
				//	->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery-ui.min.js') )
					

					->appendFile ( $this->baseUrl ('/public/ckeditor/ckeditor.js') )
					->appendFile ( $this->baseUrl ('/public/ckfinder/ckfinder.js') )
				
					;
				
		?>
        
		<script>
            $(function(){
              center()//gọi hàm mới load web
                $(window).resize(function(){center()})//gọi hàm khi resize
        		//alert($(window).width());
        		//alert($('#thongbao').width());
              function center(){//hàm xử lý
                $('#thongbao').css({left:($(window).width()-$('#thongbao').width())/2,top:(($(window).height()-$('#abc').height())/2)-150})
              }
            })
          </script>
		
	</head>
    <body>
	<div id="bg_thongbao"></div>
	<div id="thongbao"></div>
    </div>
    <?php  echo $this->render('_header.phtml')?>
	<div id="" class="wrapper">
	<div class="container">

	<?php
	$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$activeindex ='';
	$activearticle ='';
	$activethisinh ='';
	$activehuongdan ='';
	
if($controllerName=='index')
{
$activeindex = 'active';
}else
if($controllerName=='article')
{
$activearticle = 'active';
}else
if($controllerName=='thisinh')
{
$activethisinh = 'active';
}else
{
$activehuongdan = 'active';
}
	?>
				<div class="list_menu">
					<ul>
                        <li class="menu">
							<a style="display: inline;" href="<?php echo APP_DOMAIN ?>/admin" target="_top">Home</a>
						</li>
						<li class="menu">
							<a style="display: inline;" href="<?php echo APP_DOMAIN ?>/admin/category" target="_top">Loại Sản Phẩm</a>
						</li>
						<li class="menu">
							<a style="display: inline;" href="<?php echo APP_DOMAIN ?>/admin/product" target="_top">Sản Phẩm</a>
						</li>	

                        <li class="menu">
							<a style="display: inline;" class="" onclick="DangXuat();" href="javascript:;" >Đăng Xuất</a>
						</li>
						
					</ul>
				</div>
				
				<div class="contents">					
					<div class="galleries_contents">	
			<center>			
			<!-- <h1><div id="title_pages">Chọn trang</div></h1> -->			
				<img id="loading" style="display: none"  src="<?php echo $this->baseUrl ('application/templates/giaodien_admin/images/loading.gif') ?>" />		
				<div id="show_pages"></div>
				
		</center>
						<div id='quanlidanhsachtrang' style="display: block"  >
								<?php echo $this->layout()->content; ?>	
						</div>
					</div>
				</div>
			<?php  echo $this->render('_footer.phtml')?>	
	</div>

	</div>
			

	</body>
</html>